clients:
  - client_id: example
    client_secret: change_me
    # OR use client_secret_file to read the secret from a file:
    # client_secret_file: /path/to/client/secret
    redirect_uris:
      - https://httpbin.org/get
discord:
  client_id: <YOUR DISCORD APPLICATION CLIENT ID>
  client_secret: <YOUR DISCORD APPLICATION CLIENT SECRET>
  # OR use client_secret_file to read the secret from a file:
  # client_secret_file: /path/to/discord/secret
url: http://localhost:3000