clients:
  - client_id: example
    client_secret: change_me
    redirect_uris:
      - https://httpbin.org/get
discord:
  client_id: <YOUR DISCORD APPLICATION CLIENT ID>
  client_secret: <YOUR DISCORD APPLICATION CLIENT SECRET>
url: http://localhost:3000